### ISSUE TITLE
Not actual issue: Trying to contact maintainer 

### ISSUE THREAD

**Issue by nannerpusser** [blackmonk13/wordament_solver#1]
Hey sorry for opening an issue ticket, but I can't find a way to contact the wordament_solver maintainer. Tried all listed methods, no dice. Some kind of form submission error on personal site. 

Anyway, I'm working on this problem myself and came across this repo and it is by far the most recent and updated python-based solver I've been able to find. I am having a hell of a time with EasyOCR and Pytesseract and getting either of them to deliver consistent results when I go to do the actual OCR after letter extraction. My solution to find and crop the grid from a screenshot uses template matching and works great (as long as screen res doesn't change), but then I hit a wall trying to clean up the cropped portion, binarize it, and get either OCR solution to play nice. I can wash the cropped grid and eventually return accurate results, but it just never works on a different input image. I'm wondering if you managed to get better results using your method of finding the score/number + finding the letter, and cropping each out for OCR separately? At least that is what it looked like, but I am unable to get any contour return when I run your app locally. It seems no matter what my inputs are, it outputs no contours found and to adjust my thresholds. Sorry again for contacting like this. Just curious if you were even still working on this or maybe had a version of image_parser.py that you hadn't pushed or something.

**Comment by blackmonk13** [comment]
Hi @nannerpusser,

I apologize for the delay in my response earlier. I noticed that the issue was closed, and I wanted to check if you were able to find a solution or if you still need assistance.

Looking forward to hearing from you!

**Comment by nannerpusser** [comment]
Well, still curious if you're working on this at all and despite the fact I'm talking to an auto-responder, I did have a couple questions about your OCR method and getting it to work as-is (if that is possible) because extracting the bounding boxes separately for score + letter then recombining is really interesting and might be the only public repo Wordament OCR on the internet that can handle it consistently (without training a custom LLM on some huge Wordament SegoeUI dataset of course).

**Comment by blackmonk13** [comment]
> Well, still curious if you're working on this at all and despite the fact I'm talking to an auto-responder, I did have a couple questions about your OCR method and getting it to work as-is (if that is possible) because extracting the bounding boxes separately for score + letter then recombining is really interesting and might be the only public repo Wordament OCR on the internet that can handle it consistently (without training a custom LLM on some huge Wordament SegoeUI dataset of course). 

I'm not an auto responder I was just away for a while. I'm not currently working on the project but I'll be glad to answer any questions you have. You can reach out to me on [telegram](https://t.me/+dWDxmV_6OZg3OGVk)
